version: "3.7"
services:
  app:
    container_name: financial-chat-bot
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - kafka
    depends_on:
      - kafka
  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    environment:
      ADVERTISED_HOST: "localhost"
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    ports:
      - 2181:2181
      - 9092:9092